### ISSUE TITLE
Used endpoint will stop working

### ISSUE THREAD

**Issue by Nekidev** [CataDev0/nekosapi#1]
https://nekos.nekidev.com/ will stop working in about 15 days. The best choice would be to move to https://v1.nekosapi.com/api/ . It points to the same host but that domain won't expire.

(Another choice would be to use https://api.nekosapi.com/v1/ but that points to nekosapi's server which proxies the connection to vercel. It'd end up making requests take more to complete)

**Comment by CataDev0** [comment]
Solved in v0.4.3 301509b
And in v0.3.3 for nodejs  >18

Thanks :smiley:
